# -*- coding: utf-8 -*-
"""Математическое ядро AMDB: алгебра многомерных матриц."""
from .convolve import (
    ALPHABET,
    MAX_SUBSCRIPTS,
    TooManyIndicesError,
    build_einsum,
    build_spec,
    convolve,
    convolve_naive,
    symbols_for,
    unit_matrix,
)
from .mdm import MultidimensionalMatrix, align, convolve_named, lambda_mu
from .ops import (
    elementwise,
    indicator,
    internal_convolution,
    masked,
    reduce_axes,
    rollup_matrix,
    rollup_reduce,
    running_sum,
    weighted_window,
)
from .signature import SYSTEM, AlgebraicSystem, Axiom, OperationSymbol, Sort
from .semiring import (
    BOOL_OR_AND,
    MAX_PLUS,
    MAX_PROD,
    MIN_PLUS,
    MIN_PROD,
    SEMIRINGS,
    SUM_PROD,
    Semiring,
    aggregate_over_axes,
    convolve_semiring,
    count_distinct,
)
from .sparse import COOCube, convolve_sparse

__all__ = [
    "ALPHABET",
    "BOOL_OR_AND",
    "AlgebraicSystem",
    "Axiom",
    "OperationSymbol",
    "SYSTEM",
    "Sort",
    "MAX_PLUS",
    "MAX_PROD",
    "MIN_PLUS",
    "MIN_PROD",
    "SEMIRINGS",
    "SUM_PROD",
    "Semiring",
    "MAX_SUBSCRIPTS",
    "TooManyIndicesError",
    "MultidimensionalMatrix",
    "COOCube",
    "aggregate_over_axes",
    "align",
    "build_einsum",
    "build_spec",
    "convolve",
    "convolve_naive",
    "convolve_named",
    "convolve_semiring",
    "convolve_sparse",
    "count_distinct",
    "elementwise",
    "indicator",
    "internal_convolution",
    "lambda_mu",
    "masked",
    "reduce_axes",
    "rollup_matrix",
    "rollup_reduce",
    "running_sum",
    "symbols_for",
    "unit_matrix",
    "weighted_window",
]
